[package]
name = "e2e-tests"
version = "0.1.0"
authors = ["repjarms <jeffarn12@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
headless_chrome = "0.9.0"
failure = "0.1.8"